-- MySQL Script generated by MySQL Workbench
-- Sat Aug 10 18:33:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cyber_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cyber_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cyber_blog` DEFAULT CHARACTER SET utf8 ;
USE `cyber_blog` ;

-- -----------------------------------------------------
-- Table `cyber_blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyber_blog`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 2 COMMENT '1 - Ativo\n2 - Bloqueado',
  `senha` VARCHAR(255) NULL,
  `thumb` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyber_blog`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyber_blog`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyber_blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyber_blog`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `palavra_chave` VARCHAR(200) NULL,
  `slug` VARCHAR(200) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 2,
  `data_publicacao` DATETIME NOT NULL,
  `thumb` VARCHAR(200) NULL,
  `users_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_posts_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `cyber_blog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `cyber_blog`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
